/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminReviewRouteImport } from './routes/admin-review'
import { Route as AdminRoadmapRouteImport } from './routes/admin-roadmap'
import { Route as AdminStudentsRouteImport } from './routes/admin-students'
import { Route as ClassRouteImport } from './routes/class'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as SprintsRouteImport } from './routes/sprints'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewRoute = AdminReviewRouteImport.update({
  id: '/admin-review',
  path: '/admin-review',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoadmapRoute = AdminRoadmapRouteImport.update({
  id: '/admin-roadmap',
  path: '/admin-roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/admin-students',
  path: '/admin-students',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassRoute = ClassRouteImport.update({
  id: '/class',
  path: '/class',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const SprintsRoute = SprintsRouteImport.update({
  id: '/sprints',
  path: '/sprints',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-review': typeof AdminReviewRoute
  '/admin-roadmap': typeof AdminRoadmapRoute
  '/admin-students': typeof AdminStudentsRoute
  '/class': typeof ClassRoute
  '/dashboard': typeof DashboardRoute
  '/roadmap': typeof RoadmapRoute
  '/sprints': typeof SprintsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-review': typeof AdminReviewRoute
  '/admin-roadmap': typeof AdminRoadmapRoute
  '/admin-students': typeof AdminStudentsRoute
  '/class': typeof ClassRoute
  '/dashboard': typeof DashboardRoute
  '/roadmap': typeof RoadmapRoute
  '/sprints': typeof SprintsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-review': typeof AdminReviewRoute
  '/admin-roadmap': typeof AdminRoadmapRoute
  '/admin-students': typeof AdminStudentsRoute
  '/class': typeof ClassRoute
  '/dashboard': typeof DashboardRoute
  '/roadmap': typeof RoadmapRoute
  '/sprints': typeof SprintsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-review'
    | '/admin-roadmap'
    | '/admin-students'
    | '/class'
    | '/dashboard'
    | '/roadmap'
    | '/sprints'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-review'
    | '/admin-roadmap'
    | '/admin-students'
    | '/class'
    | '/dashboard'
    | '/roadmap'
    | '/sprints'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-review'
    | '/admin-roadmap'
    | '/admin-students'
    | '/class'
    | '/dashboard'
    | '/roadmap'
    | '/sprints'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminReviewRoute: typeof AdminReviewRoute
  AdminRoadmapRoute: typeof AdminRoadmapRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  ClassRoute: typeof ClassRoute
  DashboardRoute: typeof DashboardRoute
  RoadmapRoute: typeof RoadmapRoute
  SprintsRoute: typeof SprintsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-review': {
      id: '/admin-review'
      path: '/admin-review'
      fullPath: '/admin-review'
      preLoaderRoute: typeof AdminReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-roadmap': {
      id: '/admin-roadmap'
      path: '/admin-roadmap'
      fullPath: '/admin-roadmap'
      preLoaderRoute: typeof AdminRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-students': {
      id: '/admin-students'
      path: '/admin-students'
      fullPath: '/admin-students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class': {
      id: '/class'
      path: '/class'
      fullPath: '/class'
      preLoaderRoute: typeof ClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sprints': {
      id: '/sprints'
      path: '/sprints'
      fullPath: '/sprints'
      preLoaderRoute: typeof SprintsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminReviewRoute: AdminReviewRoute,
  AdminRoadmapRoute: AdminRoadmapRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  ClassRoute: ClassRoute,
  DashboardRoute: DashboardRoute,
  RoadmapRoute: RoadmapRoute,
  SprintsRoute: SprintsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
